# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
on:
  push:
    branches:
      - feature/githubactions
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
## Cache the maven dependencies to speed up the build process
    - name: Set Project Version and Extract Version from pom.xml ## Setting the project version and extracting the version from pom.xml for further use
      id: set_and_extract_version
      run: |
          mvn -q versions:set -DnewVersion=1.0.0
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      working-directory: myapp

    - name: Clean, Compile, and Run Java Application #Cleaning & Running the application before packaging to jar
      run: mvn -q clean compile exec:java
      working-directory: myapp

    - name: Build & run packged  Java application #Packaging the application to jar and running the jar
      run: |
        mvn -B package --file pom.xml > /dev/null
        java -jar target/myapp-${{ env.VERSION }}.jar com.myapp.app.App
      working-directory: myapp
      if : success() ## Only run if the previous step is successful


